from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel
import networkx as nx
import ast

from backend.services import graph_store
from graph.centrality import compute_resilience_index

router = APIRouter()


class SimRequest(BaseModel):
    node_id: str


@router.post("/simulate")
def simulate_removal(req: SimRequest):
    """
    Simulate failure of a road junction and compute
    resilience metrics on the current road graph.
    """

    # -----------------------------------------
    # Get latest graph generated by pipeline
    # -----------------------------------------

    G = graph_store.get_graph()

    if G is None:
        raise HTTPException(
            status_code=400,
            detail="No graph found. Please run /api/pipeline first."
        )

    # -----------------------------------------
    # Convert string to tuple
    # -----------------------------------------

    try:
        node = tuple(ast.literal_eval(req.node_id))
    except Exception:
        node = req.node_id

    # -----------------------------------------
    # DEBUG: Print all nodes
    # -----------------------------------------

    print("\n========== GRAPH NODES ==========")
    print(list(G.nodes()))
    print("Requested Node:", node)
    print("=================================\n")

    G = G.copy()

    # -----------------------------------------
    # Validate node
    # -----------------------------------------

    if node not in G.nodes:
        raise HTTPException(
            status_code=404,
            detail=f"Node '{node}' not found."
        )

    # -----------------------------------------
    # Metrics BEFORE removal
    # -----------------------------------------

    before_nodes = G.number_of_nodes()
    before_edges = G.number_of_edges()
    before_components = nx.number_connected_components(G)

    largest_before = max(nx.connected_components(G), key=len)
    before_lcc = len(largest_before)

    # -----------------------------------------
    # Remove Node
    # -----------------------------------------

    G.remove_node(node)

    # -----------------------------------------
    # Metrics AFTER removal
    # -----------------------------------------

    after_nodes = G.number_of_nodes()
    after_edges = G.number_of_edges()
    after_components = nx.number_connected_components(G)

    if G.number_of_nodes() > 0:
        largest_after = max(nx.connected_components(G), key=len)
        after_lcc = len(largest_after)
    else:
        after_lcc = 0

    # -----------------------------------------
    # Resilience
    # -----------------------------------------

    resilience = compute_resilience_index(
        graph_store.get_graph(),
        [node]
    )

    resilience_score = None

    if resilience:
        resilience_score = resilience[0]["resilience_index"]

    # -----------------------------------------
    # Damage %
    # -----------------------------------------

    if before_lcc == 0:
        damage = 100
    else:
        damage = round(
            ((before_lcc - after_lcc) / before_lcc) * 100,
            2
        )

    # -----------------------------------------
    # AI Recommendation
    # -----------------------------------------

    if damage > 50:
        recommendation = (
            "Critical junction detected. "
            "Construct an alternate road connection."
        )
    elif damage > 20:
        recommendation = (
            "Moderate impact. "
            "Consider adding redundancy."
        )
    else:
        recommendation = (
            "Low impact. Network remains resilient."
        )

    # -----------------------------------------
    # Response
    # -----------------------------------------

    return JSONResponse(
        {
            "removed_node": str(node),
            "before": {
                "nodes": before_nodes,
                "edges": before_edges,
                "components": before_components,
                "largest_component": before_lcc,
            },
            "after": {
                "nodes": after_nodes,
                "edges": after_edges,
                "components": after_components,
                "largest_component": after_lcc,
            },
            "resilience_index": resilience_score,
            "network_damage_percent": damage,
            "ai_recommendation": recommendation,
        }
    )